version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
